name: Jekyll Themes
url: https://raghavinthecloud.github.io/jekyllthemes/
description: Insert tagline here

permalink: /themes/:title/

gems: [jekyll-paginate]

highlighter: pygments
paginate: 20



exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'vendor']
